name: Build and Publish

on:
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install cross-env
      run: npm install -g cross-env
      
    - name: Compile and Package
      run: npm run package
      env:
        CI: true

    - name: Extract Package Version
      id: package_version
      uses: Saionaro/extract-package-version@v1.2.1    

    - name: Publish
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name}}.vsix
        path: |
          "**/*.vsix"

    - name: Tag and Release
      id: tag_release
      uses: softprops/action-gh-release@v1
      with:
        body: Release ${{ steps.package_version.outputs.version }}
        tag_name: ${{ steps.package_version.outputs.version }}
        generate_release_notes: true
        files: |
          **/*.vsix